version: '3.4'

services:
  catalogdb:
    container_name: catalog-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyPass123"
    ports:
      - "1433:1433"
    volumes:
      - mssql_catalog:/var/opt/mssql

  distributedcache:
    container_name: distributed-cache
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=111
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=catalogdb;Database=CoffeeShop_Catalog;User=sa;Password=MyPass123
    depends_on:
      - catalogdb
      - distributedcache
    ports:
      - "7000:8080"
      - "7070:8081"
    volumes:
       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
       - ${USERPROFILE}/.aspnet/https:/https:ro

  shoppingCartdb:
    container_name: shopping-cart-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ShoppingCartDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_shoppingcart:/var/lib/postgresql/data/

  shoppingCart.api:
    container_name: shopping-cart-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=111
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=shoppingcartdb;Port=5432;Database=ShoppingCartDb;User Id=postgres;Password=postgres
      - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - shoppingCartdb
      - distributedcache
    ports:
      - "7001:8080"
      - "7071:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

  apigateway:
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=111
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalog.api
      - shoppingCart.api
    ports:
      - "7005:8080"
      - "7075:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro
