version: '3.4'

services:
  catalogdb:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/catalogapi:${TAG}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  distributedcache:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/distributedcache:${TAG}
    build:
      context: .
      dockerfile: Services/DistributedCache/Dockerfile 

  catalog.api:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/catalogapi:${TAG}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  shoppingCartdb:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/shoppingcartdb:${TAG}
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCartDb/Dockerfile 

  shoppingCart.api:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/shoppingcartapi:${TAG}
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.API/Dockerfile

  messagebroker:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/messagebroker:${TAG}
    build:
      context: .
      dockerfile: Services/MessageBroker/Dockerfile  

  apigateway:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/apigateway:${TAG}
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

  orderdb:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/orderdb:${TAG}
    build:
      context: .
      dockerfile: Services/Ordering/OrderDb/Dockerfile 

  ordering.api:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/orderingapi:${TAG}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  identitydb:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/identitydb:${TAG}
    build:
      context: .
      dockerfile: Services/IdentityDb/Dockerfile  

  auth.api:
    image: ${CONTAINER_REGISTRY_LOGIN_SERVER}/authapi:${TAG}
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile

volumes:
  mssql_catalog:
  postgres_shoppingcart:
