on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20250219184953
  RESOURCE_GROUP: coffee-shop-backend
  CONTAINER_REGISTRY_NAME: coffeeshopbackend
  CONTAINER_REGISTRY_LOGIN_SERVER: coffeeshopbackend.azurecr.io
  CONTAINER_APP_NAME: coffee-shop-aca

jobs:
  SetupAzureResources:
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.managedEnv20250219184953_SPN }}
    
    - name: Create Azure Container Registry (if not exists)
      run: |
        az acr show --name ${{ env.CONTAINER_REGISTRY_NAME }} || \
        az acr create --name ${{ env.CONTAINER_REGISTRY_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --sku Basic
    
    - name: Create Azure Container App (if not exists)
      run: |
        az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} || \
        az containerapp create --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --environment ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }} \
          --image nginx \
          --target-port 80 \
          --ingress external

  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    needs: SetupAzureResources
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Загружает всю историю и все файлы
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.managedEnv20250219184953_SPN }}
    
    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
        
    - name: List files in a specific directory
      run: |
       ls -l ./src 

    - name: Build and push Docker images using Docker Compose
      run: |
        docker-compose -f ./docker-compose.yml build
        echo "${{ secrets.coffeeshopbackend_PASSWORD }}" | docker login ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.coffeeshopbackend_USERNAME }} --password-stdin
        docker-compose -f ./docker-compose.yml push

    - name: Deploy containers to Azure Container Apps
      run: |
        az containerapp update \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --add-container name=apigateway image=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/apigateway:${{ github.sha }} \
          --add-container name=auth-api image=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/auth-api:${{ github.sha }} \
          --add-container name=catalog-api image=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/catalog-api:${{ github.sha }} \
          --add-container name=ordering-api image=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/ordering-api:${{ github.sha }} \
          --add-container name=shoppingcart-api image=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/shoppingcart-api:${{ github.sha }}
