name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20250219184953
  RESOURCE_GROUP: coffee-shop-backend
  CONTAINER_REGISTRY_NAME: coffeshopbackend
  CONTAINER_REGISTRY_LOGIN_SERVER: coffeeshopbackend.azurecr.io
  CONTAINER_APP_NAME: coffee-shop-backend
  TAG: ${{ github.sha }}

jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.managedEnv20250219184953_SPN }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.CONTAINER_REGISTRY_NAME }}

      - name: Deploy containers to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
            azure_credentials: ${{ secrets.managedEnv20250219184953_SPN }}
            resource_group: ${{ env.RESOURCE_GROUP }}
            container_app_name: ${{ env.CONTAINER_APP_NAME }}
            imageToDeploy: |
              ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/catalogapi:${{ env.TAG }}
              ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/shoppingcartapi:${{ env.TAG }}
              ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/apigateway:${{ env.TAG }}
              ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/orderingapi:${{ env.TAG }}
              ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/authapi:${{ env.TAG }}
