on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20250219184953
  RESOURCE_GROUP: coffee-shop-backend
  CONTAINER_REGISTRY_NAME: coffeeshopbackend
  CONTAINER_REGISTRY_LOGIN_SERVER: coffeeshopbackend.azurecr.io
  CONTAINER_APP_NAME: coffee-shop-aca

jobs:
  SetupAzureResources:
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.managedEnv20250219184953_SPN }}
    
    - name: Create Azure Container Registry (if not exists)
      run: |
        az acr show --name ${{ env.CONTAINER_REGISTRY_NAME }} || \
        az acr create --name ${{ env.CONTAINER_REGISTRY_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --sku Basic
    
    - name: Create Azure Container App (if not exists)
      run: |
        az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} || \
        az containerapp create --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --environment ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }} \
          --image nginx \
          --target-port 80 \
          --ingress external

  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    needs: SetupAzureResources
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: List files in a specific directory
      run: ls -l ./src 
    
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.managedEnv20250219184953_SPN }}
      
    - name: Login to Azure Container Registry
      run: az acr login --name ${{ env.CONTAINER_REGISTRY_NAME }}

    - name: Build and push Docker images using Docker Compose
      run: |
        TAG=${{ github.sha }}

        docker-compose -f ./src/docker-compose.yml build --no-cache

        SERVICES=$(docker-compose -f ./src/docker-compose.yml config --services)

        for SERVICE in $SERVICES; do
          docker tag $SERVICE ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/$SERVICE:$TAG
          docker push ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/$SERVICE:$TAG
        done

    - name: Deploy containers to Azure Container Apps
      run: |
        SERVICES=$(docker-compose -f ./src/docker-compose.yml config --services)
        UPDATE_COMMAND="az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}"
        
        for SERVICE in $SERVICES; do
          UPDATE_COMMAND="$UPDATE_COMMAND --add-container name=$SERVICE image=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/$SERVICE:${{ github.sha }}"
        done

        echo "Executing: $UPDATE_COMMAND"
        eval $UPDATE_COMMAND
